set -e
export PGPASSWORD=$POSTGRES_PASSWORD;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $POSTGRES_DATABASE_USERNAME WITH PASSWORD '$POSTGRES_DATABASE_PASSWORD';
  CREATE DATABASE $POSTGRES_TEST_DB;
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_TEST_DB TO $POSTGRES_DATABASE_USERNAME;
EOSQL
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $POSTGRES_DATABASE_USERNAME WITH PASSWORD '$POSTGRES_DATABASE_PASSWORD';
	CREATE DATABASE $POSTGRES_DB;
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_DATABASE_USERNAME;
EOSQL
