version: '2.2'
#
# services
services:
  # postgres
  x-postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_TEST_DB: ${POSTGRES_TEST_DATABASE_NAME}
      POSTGRES_DATABASE_USERNAME: ${POSTGRES_DATABASE_USERNAME}
      POSTGRES_DATABASE_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
      PGDATA: /data/postgres
    hostname: ${POSTGRES_HOST}
    networks:
      - xnetwork
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    restart: unless-stopped
    volumes:
       - ./volumes/postgres:/var/lib/postgresql/data
       - ./scripts/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
  # pgweb
  x-pgweb:
    image: sosedoff/pgweb
    depends_on:
      - x-postgres
    networks:
      - xnetwork
    ports:
      - 127.0.0.1:${PGWEB_PORT}:8081
    restart: unless-stopped
    volumes:
      - ./volumes/pgweb:/var/lib/pgweb
networks:
  xnetwork:
    external: true